cacheFolder: d:/.yarn-cache

enableConstraintsChecks: true

enableHardenedMode: true

enableInlineHunks: true

globalFolder: d:/.yarn-global

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.9.2.cjs
